[theme]

# Primary accent for interactive elements
primaryColor = '#AAE0DA'

# Background color for the main content area
backgroundColor = '#11111C'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1C1C2A'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"